GymManagmentSystem/Controllers/ClassesController.cs
using BLL;
using GymManagmentSystem.ModelBinding;
using GymManagmentSystem.Models.ClassModels;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymManagmentSystem.Controllers
{
    public class ClassesController : Controller
    {
        // GET: Classes
        public ActionResult Index()
        {
            ClassBL classBL = new ClassBL();
            List<Class> classesList = new List<Class>();
            classesList = classBL.Read();

            List<ClassModel> classes = new List<ClassModel>();
            classes = FillModel(classesList);

            return View("List", classes);
        }

        public ActionResult Insert()
        {
            return View("Insert", new ClassModel());
        }

        public ActionResult Save([ModelBinder(typeof(ClassModelBinder))]ClassModel classModel, string classId)
        {
            Class @class = new Class
            {
                AddedOn = DateTime.Now,
                Name = classModel.SportName,
                Days = classModel.Days,
                Hours = classModel.Hours,
                AddedBy = 1,// TO DO :: change it later
                Cost = classModel.Membership,
                Hall = classModel.Hall,
                MaxCount = classModel.MaxCount,
                EmployeeId = classModel.TrainerId
            };

            if (classModel.StartDate != null)
            {
                @class.StartDate = DateTime.Parse(classModel.StartDate);
            }

            if (classModel.EndDate != null)
            {
                @class.EndDate = DateTime.Parse(classModel.EndDate);
            }

            ClassBL classBL = new ClassBL();
            if (string.IsNullOrEmpty(classId))
            {
                classBL.Insert(@class);
            }
            else
            {
                @class.ID = @class.ID = int.Parse(classId);
                classBL.Update(@class);
            }


            List<Class> classesList = new List<Class>();
            classesList = classBL.Read();

            List<ClassModel> classes = new List<ClassModel>();

            classes = FillModel(classesList);

            return View("List", classes);
        }

        [HttpGet]
        public JsonResult GetSports()
        {
            try
            {
                TitleBL titleBL = new TitleBL();
                Dictionary<int, string> sportsDic = titleBL.GetSports();
                List<SportModel> sports = new List<SportModel>();
                
                foreach (var item in sportsDic)
                {
                    SportModel sprt = new SportModel
                    {
                        Id = item.Key
                    };
                    string name = item.Value;
                    if (name.Split(' ').Last().ToLower() == "trainer")
                    {
                        sprt.Name = item.Value.Substring(0, name.IndexOf(name.Split(' ').Last()));
                    }
                    else
                    {
                        sprt.Name = item.Value;
                    }
                    sports.Add(sprt);
                }
                JsonResult json = Json(sports, JsonRequestBehavior.AllowGet);
                return json;
            }
            catch
            {
                throw;// TO DO :: config it latter
            }
        }

        [HttpGet]
        public JsonResult GetTrainers(string sportId)
        {
            EmployeeBL employeeBL = new EmployeeBL();
            Dictionary<int, string> trainersList = employeeBL.GetTrainers(int.Parse(sportId));

            List<TrainerModel> trainers = new List<TrainerModel>();
            foreach (var item in trainersList)
            {
                trainers.Add(new TrainerModel
                {
                    Id = item.Key,
                    Name = item.Value
                });
            }

            JsonResult json = Json(trainers, JsonRequestBehavior.AllowGet);
            return json;
        }

        [NonAction]
        private List<ClassModel> FillModel(List<Class> classesList)
        {
            Employee emp = new Employee();
            List<ClassModel> classes = new List<ClassModel>();
            foreach (var item in classesList)
            {
                emp = item.Employee;
                classes.Add(new ClassModel
                {
                    Id = item.ID,
                    SportName = item.Name,
                    Days = item.Days,
                    Hours = item.Hours,
                    Membership = item.Cost,
                    Hall = item.Hall,
                    Count = item.Count,
                    MaxCount = item.MaxCount,
                    TrainerId = item.EmployeeId,
                    TrainerName = emp.Name1 + " " + emp.Name2 + " " + emp.Name4
                });
            }

            return classes;
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            ViewBag.id = id;
            return View("Insert");
        }

        public void Delete(string id)
        {
            ClassBL classBL = new ClassBL();
            classBL.Datete(int.Parse(id));
        }

        public JsonResult GetClass(string sportId)
        {
            ClassBL classBL = new ClassBL();
            Class @class = new Class();
            @class = classBL.Read(int.Parse(sportId));

            ClassModel classModel = new ClassModel
            {
                Id = @class.ID,

                //SportId = @class.Employee.TitleID,
                //TrainerId = @class.EmployeeID,
                Days = @class.Days,
                Hours = @class.Hours,
                StartDate = @class.StartDate.ToString(),
                EndDate = @class.EndDate.ToString(),
                Membership = @class.Cost,
                Hall = @class.Hall,
                Count = @class.Count,
                MaxCount = @class.MaxCount,
            };

            JsonResult json = Json(classModel, JsonRequestBehavior.AllowGet);

            return json;
        }

        [HttpGet]
        public JsonResult GetUnavailableTimes(string trainerId, string days)
        {
            ClassBL classBL = new ClassBL();
            string[] classesTime = classBL.GetUnavailableTimes(int.Parse(trainerId), days);
            if (classesTime == null)
                return null;

            JsonResult json = Json(classesTime, JsonRequestBehavior.AllowGet);
            return json;
        }

    }
}

GymManagmentSystem/Views/Classes/Insert.cshtml
@model GymManagmentSystem.Models.ClassModels.ClassModel
@if (ViewBag.id == null)
{
    <h2 id="pageStatus">Insert</h2>
}
else
{
    <h2 id="pageStatus">Update</h2>
}

<html>
<head>
    <script>
        var Times = [
            "08:00-09:30 am",
            "09:30-11:00 am",
            "11:00-12:30 pm",
            "12:30-02:00 pm",
            "02:00-03:30 pm",
            "03:30-05:00 pm",
            "05:00-06:30 pm",
            "06:30-08:00 pm"
        ];



        $(document).ready(function () {
            $.ajax({
                method: 'get',
                url: '/Classes/GetSports',
                data: {},
                success: function (data) {
                    FillSports(data);
                },
                error: function () {
                    debugger;
                }
            });

            if (document.getElementById("pageStatus").innerHTML == "Update") {
                PrepareToUpdate(@ViewBag.id);
            } else {

            }
        });

        function PrepareToUpdate(id) {
            $.ajax({
                method: 'get',
                url: '/Classes/GetClass',
                data: { sportId: id },
                success: function (data) {
                    FillAllFialds(data);
                },
                error: function () {

                }
            });

        }

        function ChangeLimitation(checkBox) {
            var cb = checkBox.checked;
            var start = document.getElementById("StartDate");
            var end = document.getElementById("EndDate");
            if (cb) {
                start.removeAttribute("hidden");
                end.removeAttribute("hidden");
            } else {
                start.setAttribute("hidden", true);
                end.setAttribute("hidden", true);
            }
        }

        function FillSports(data) {
            $("#sSports").append("<option value='0'> --Select Sport-- </option>");
            for (var index in data) {
                $("#sSports").append("<option value='" + data[index].Id + "'>" + data[index].Name + "</option>");
            }
        }

        function FillTrainersSelect(data) {
            $('#sTrainers').find('option').remove().end();
            $("#sTrainers").append("<option value='0'>--Select Trainer--</option>");
            for (var index in data) {
                $("#sTrainers").append("<option value='" + data[index].Id + "'>" + data[index].Name + "</option>");
            }
        }

        function FillTrainersSelectForUpdate(data, trainerId) {
            $('#sTrainers').find('option').remove().end();
            $("#sTrainers").append("<option value='0'>--Select Trainer--</option>");
            for (var index in data) {
                if (data[index].Id == trainerId) {
                    $("#sTrainers").append("<option value='" + data[index].Id + "' selected>" + data[index].Name + "</option>");
                } else {
                    $("#sTrainers").append("<option value='" + data[index].Id + "'>" + data[index].Name + "</option>");
                }

            }
        }

        function GetTrainers(sportId) {
            if (sportId != null) {
                $.ajax({
                    method: "get",
                    url: "/Classes/GetTrainers",
                    data: {
                        sportId: sportId
                    },
                    success: function (data) {
                        // flag
                        FillTrainersSelect(data);
                    },
                    error: function () {
                    }
                });
            }

        }

        function GetTrainersForUpdate(sportId, trainerId) {
            if (sportId != null) {
                $.ajax({
                    method: "get",
                    url: "/Classes/GetTrainers",
                    data: {
                        sportId: sportId
                    },
                    success: function (data) {
                        // flag
                        FillTrainersSelectForUpdate(data, trainerId);
                    },
                    error: function () {
                    }
                });
            }

        }

        function FillAllFialds(data) {
            document.getElementById("sSports").value = data.SportId;
            document.getElementById("sDays").value = data.Days;
            document.getElementById("sHours").value = data.Hours;
            if (data.StartDate !== "") {
                document.getElementById("cbIsLimited").checked = true;
                document.getElementById("StartDate").hidden = false;
                document.getElementById("EndDate").hidden = false;
                GetValidDate(document.getElementById("txtStartDate"), data.StartDate);
                GetValidDate(document.getElementById("txtEndDate"), data.EndDate);
                //document.getElementById("txtStartDate").value = data.StartDate;
                //document.getElementById("txtEndDate").value = data.EndDate;
            }
            document.getElementById("txtMembership").value = data.Membership;
            document.getElementById("txtHall").value = data.Hall;
            document.getElementById("txtMax").value = data.MaxCount;
            GetTrainersForUpdate(data.SportId, data.TrainerId);
            document.getElementById("btnSave").value = "Update";
        }

        function SetTrainer(trainerId) {
            debugger;
            document.getElementById("sTrainers").value = data.TrainerId;
        }

        function GetValidDate(element, strDate) {
            var x = strDate.indexOf(" ");
            debugger
            var date = strDate.substring(0, strDate.indexOf(" "));
            var lisDate = date.split("/");
            var day = lisDate[0];;
            var mounth = lisDate[1];
            if (lisDate[0].length == 1)
                day = "0" + lisDate[0];
            if (lisDate[1].length == 1)
                mounth = "0" + lisDate[1];
            var validDate = lisDate[2] + "-" + day + "-" + mounth;
            element.value = validDate;
        }

        function SetClassTime(days) {

            $('#sHours').find('option').remove();


            $("#sHours").append("<option value='0' selected>--Select--</option>");
            if (days != "Daily") {
                var trainerId = document.getElementById("sTrainers").value;
                $.ajax({
                    method: "get",
                    url: "/Classes/GetUnavailableTimes",
                    data: {
                        trainerId: trainerId,
                        days: days
                    },
                    success: function (data) {
                        var timesArr = [];
                        timesArr = Times;
                        for (var index in data) {
                            for (var item in Times) {
                                if (data[index] == Times[item]) {
                                    timesArr.splice(item, 1);
                                }
                            }
                        }

                        for (var opt in timesArr) {
                            $("#sHours").append("<option value='" + timesArr[opt] + "' selected>" + timesArr[opt] + "</option>");
                        }

                    },
                    error: function (ex) {
                        debugger;
                    }
                });
            } else {
                debugger;
                for (var item in Times) {
                    $("#sHours").append("<option value='" + Times[item] + "' selected>" + Times[item] + "</option>");
                }
            }

        }

    </script>
    <style>
        .row {
            margin-bottom: 2px;
        }
    </style>
</head>

<body>
    <div class="container">
        @using (Html.BeginForm("Save", "Classes", new { classId = @ViewBag.id }, FormMethod.Post))
        {
            <div class="form-group row">
                <label for="sSports" class="col-sm-4 control-label">Sport Name:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="sSports" name="sSports" onchange="GetTrainers(this.value)">
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="sTrainers" class="col-sm-4 control-label">Trainer Name:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="sTrainers" name="sTrainers">
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="sDays" class="col-sm-4 control-label">Days:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="sDays" name="sDays" onchange="SetClassTime(this.value)">
                        @foreach (var item in Model.DaysTime)
                        {
                            <option value="@item">@item</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="sHours" class="col-sm-4 control-label">Hours:</label>
                <div class="col-sm-8">
                    <select class="form-control" id="sHours" name="sHours">
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-4 control-label" for="cbIsLimited">It's Limited:</label>
                <div class="col-sm-2">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="cbIsLimited" name="cbIsLimited" onclick="ChangeLimitation(this)">
                    </div>
                </div>
            </div>

            <div id="StartDate" class="form-group row" hidden>
                <label for="txtStartDate" class="col-sm-4 control-label">Start Date:</label>
                <div class="col-sm-8">
                    <input type="date" id="txtStartDate" name="txtStartDate" class="form-control">
                </div>
            </div>

            <div id="EndDate" class="form-group row" hidden>
                <label for="txtEndDate" class="col-sm-4 control-label">End Date:</label>
                <div class="col-sm-8">
                    <input type="date" id="txtEndDate" name="txtEndDate" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="txtMembership" class="col-sm-4 control-label">Membership:</label>
                <div class="col-sm-8">
                    <input type="text" id="txtMembership" name="txtMembership" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="txtHall" class="col-sm-4 control-label">Hall:</label>
                <div class="col-sm-8">
                    <input type="text" id="txtHall" name="txtHall" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="txtMax" class="col-sm-4 control-label">Maximum Members:</label>
                <div class="col-sm-8">
                    <input type="number" id="txtMax" name="txtMax" class="form-control">
                </div>
            </div>

            <div class="button my-2">
                <input type="submit" class="btn btn-form " id="btnSave" name="btnSave" value="Save">
            </div>
        }
    </div>
</body>

</html>

GymManagmentSystem/Views/Classes/List.cshtml
@model List<GymManagmentSystem.Models.ClassModels.ClassModel>
@{
    ViewBag.Title = "List";
}
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .btn {
            background-color: DodgerBlue;
            border: none;
            color: white;
            padding: 2px 6px;
            font-size: 16px;
            cursor: pointer;
        }

        .img {
            background-color: rgba(152, 228, 220, 0.34)
        }

        table {
            background: url('../../background Images/classBackground.jpg');
            background-size: 100% 100%;
        }
    </style>
    <script>
        function Delete(Id) {
            //debugger;
            $.ajax({
                type: "post",
                url: "/Employees/Delete",
                data: { id: Id },
                success: function () {
                    location.reload();
                },
                error: function () {
                    alert("failed to delete");
                }
            });
        }
        function Update(Id) {

            window.location.href = window.location.origin + "/Classes/update/" + Id;

        }
    </script>
</head>
<body style="background-color:rgba(152, 228, 220, 0.34)">
    <div class="container mt-5">
        <div>
            <h2 class="text-center mb-3 text-secondary bg-light rounded-lg py-3">Classes</h2>
        </div>
        @if (!Model.Any())
        {
            <h1 style="font:italic;color:red">
                There are no classes
            </h1>
        }
        else
        {
            int count = 0;
            <table class="table">
                <thead class="thead thead-title">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Sport</th>
                        <th scope="col">Trainer Name</th>
                        <th scope="col">Days</th>
                        <th scope="col">Hours</th>
                        <th scope="col">Hall</th>
                        <th scope="col">Membership</th>
                        <th scope="col">Count</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="tbody-title">
                    @foreach (var item in Model)
                    {
                        string name = item.SportName;
                        count++;
                        name = name.Substring(0, name.IndexOf("Trainer") - 1);
                        <tr>
                            <th scope="row">@count</th>
                            <td>@name</td>
                            <td>@item.TrainerName</td>
                            <td>@item.Days</td>
                            <td>@item.Hours</td>
                            <td>@item.Hall</td>
                            <td>@item.Membership JOD/Month</td>
                            <td>@item.Count/@item.MaxCount</td>
                            <td class="table-actions">
                                <div class="actions">
                                    <a onclick="Update(@item.Id)"><i class="fas fa-user-edit "></i></a>
                                    <a onclick="Delete(@item.Id)"><i class="fas fa-user-times "></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</body>
</html>