GymManagmentSystem/Controllers/MembersController.cs
using BLL;
using GymManagmentSystem.ModelBinding;
using GymManagmentSystem.Models.MemberModels;
using Models;
using Models.CustomModels.ClassModels;
using Models.CustomModels.MemberModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymManagmentSystem.Controllers
{
    public class MembersController : Controller
    {
        // GET: Members
        public ActionResult Index()
        {
            return View("List", GetMembers());
        }

        public ActionResult Insert()
        {
            return View();
        }

        public ActionResult Save([ModelBinder(typeof(MemberBinding))] MemberModel memberModel,
            HttpPostedFileBase personImage, HttpPostedFileBase idImage, string memberId)
        {

            Member member = new Member
            {
                Name1 = memberModel.Name1,
                Name2 = memberModel.Name2,
                Name3 = memberModel.Name3,
                Name4 = memberModel.Name4,
                Gender = memberModel.Gender,
                NationalID = memberModel.NationalID,
                BirthDate = memberModel.BirthDate,
                MartialState = memberModel.MartialState,
                Address = memberModel.Address,
                PhoneNo1 = memberModel.PhoneNo1,
                PhoneNo2 = memberModel.PhoneNo2,
                Email = memberModel.Email,
                //Balance = memberModel.Balance,
                MembershipExpired = memberModel.MembershipExpired,
                AddedBy = 1, //TO DO Config it later 


            };



            if (personImage != null)
            {
                byte[] personByets = new byte[personImage.ContentLength];
                personImage.InputStream.Read(personByets, 0, personImage.ContentLength);

                member.Image = personByets;
            }

            if (idImage != null)
            {
                byte[] idByets = new byte[idImage.ContentLength];
                idImage.InputStream.Read(idByets, 0, idImage.ContentLength);

                member.IdentityImage = idByets;
            }

            if (memberModel.IsStarted)
            {
                member.MembershipStart = DateTime.Now;
            }
            else
            {
                member.MembershipStart = memberModel.MembershipStart;
            }
            MemberBL memberBL = new MemberBL();
            if (memberId == null)
            {
                memberBL.Enrollment(member, memberModel.ClassId);
            }
            else
            {
                int id = int.Parse(memberId);
                member.ID = id;
                memberBL.Update(member);
            }

            return View("List", GetMembers());
        }

        [HttpGet]
        public JsonResult GetClasses()
        {
            ClassBL classBL = new ClassBL();
            List<ClassCustomModel> classes = new List<ClassCustomModel>();
            classes = classBL.GetClasses();

            JsonResult json = Json(classes, JsonRequestBehavior.AllowGet);
            return json;
        }

        [NonAction]
        private MemClassModel GetMembers()
        {
            MemberBL memberBL = new MemberBL();
            List<ListMemberModel> members = new List<ListMemberModel>();
            List<MemCustomModel> membersList = new List<MemCustomModel>();

            List<ClassModel> classes = new List<ClassModel>();
            List<ClassCustomModel> customClassModelList = new List<ClassCustomModel>();
            ClassBL classBL = new ClassBL();

            membersList = memberBL.MembersForList();
            foreach (var item in membersList)
            {
                List<ClassCustomModel> membClasses = memberBL.GetClasses(item.Id);
                members.Add(new ListMemberModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    StartDate = item.StartDate,
                    ExbiryDate = item.ExbiryDate,
                    PhoneNumber = item.PhoneNumber,
                    Image = item.Image,
                    Classes = membClasses
                });
            }

            customClassModelList = classBL.GetClasses();

            foreach (var item in customClassModelList)
            {
                classes.Add(new ClassModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    Trainer = item.Trainer,
                    DayTime = item.DayTime
                });
            }

            MemClassModel memAndClass = new MemClassModel
            {
                Mems = members,
                Classes = classes
            };

            return memAndClass;
        }

        [HttpGet]
        public ActionResult Enrollment(string classId, string memberId)
        {
            int clsId = int.Parse(classId);
            int memId = int.Parse(memberId);

            Class @class = new Class();
            Member member = new Member();

            ClassBL classBL = new ClassBL();
            MemberBL memberBL = new MemberBL();

            @class = classBL.Read(clsId);
            member = memberBL.Read(memId);

            @class.Members.Add(member);
            //member.Classes.Add(@class);

            classBL.Update(@class);
            //memberBL.Update(member);


            return null;
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            MemberBL memberBL = new MemberBL();
            memberBL.Datete(int.Parse(id));

            return View("List", GetMembers());

        }

        [HttpGet]
        public ActionResult Update(string id)
        {
            ViewBag.id = id;
            return View("Insert");
        }

        [HttpGet]
        public JsonResult GetMember(string memId)
        {
            Member member = new Member();
            MemberBL memberBL = new MemberBL();
            member = memberBL.Read(int.Parse(memId));

            MemberModel memberModel = new MemberModel
            {
                Id = member.ID,
                Name1 = member.Name1,
                Name2 = member.Name2,
                Name3 = member.Name3,
                Name4 = member.Name4,
                Gender = member.Gender,
                NationalID = member.NationalID,
                PhoneNo1 = member.PhoneNo1,
                PhoneNo2 = member.PhoneNo2,
                Email = member.Email,
                Address = member.Address,
                
            };

            JsonResult json = Json(memberModel, JsonRequestBehavior.AllowGet);
            return json;
        }
    }
}

GymManagmentSystem/Views/Members/Enrollment.cshtml
@{
    ViewBag.Title = "Enrollment";
}

<h2>Enrollment</h2>

<html>
<head>
    <script>
        $(document).ready(function () {
            
        });
    </script>
</head>
<body>

</body>
</html>

GymManagmentSystem/Views/Members/Insert.cshtml
@{
    ViewBag.Title = "Insert";
}

<html>
<head>
    <title>
        INSERT MEMBER
    </title>
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '/Members/GetClasses',
                method: 'get',
                data: {},
                success: function (data) {
                    
                    $("#ddlClasses").append("<option value='0'> --Select Sport-- </option>");
                    for (var index in data) {
                        $("#ddlClasses").append("<option value='" + data[index].Id + "'>" + data[index].Name
                            + ' / ' + data[index].Trainer + ' / ' + data[index].DayTime + "</option>");
                    }
                },
                error: function (error) {
                    debugger;
                }
            });

            if (document.getElementById("pageStatus").innerHTML == "Update") {
                prepareToUpdate(@ViewBag.id);
                document.getElementById("btnSave").value = "Update";
            }
        });

        function prepareToUpdate(Id) {
            $.ajax({
                method: "get",
                url: "/Members/GetMember",
                data: {
                    memId: Id
                },
                success: function (data) {
                    alert("done");
                    FillAllFields(data)
                },
                error: function () {
                    alert("failed to get data");
                }
            });
        }

        function setStarted() {
            var visable = document.getElementById("cbStarted").checked;
            document.getElementById("starting").hidden = visable;

        }

        function fileSelectedPersonal(input) {
            /**/
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgPersonal')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
            /**/
        }

        function fileSelectedId(input) {
            /**/
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgId')
                        .attr('src', e.target.result)
                        .width(200)
                        .height(200);
                };

                reader.readAsDataURL(input.files[0]);
            }
            /**/
        }

        function FillAllFields(data) {
            document.getElementById("txtFirstName").value = data.Name1;
            document.getElementById("txtSecondName").value = data.Name2;
            document.getElementById("txtThirdName").value = data.Name3;
            document.getElementById("txtFourthName").value = data.Name4;
            document.getElementById("ddlGender").value = data.Gender;
            document.getElementById("txtNationalId").value = data.NationalID;
            document.getElementById("imgPersonal").src = "data:image/png;base64," + data.Image;
            document.getElementById("imgId").src = "data:image/png;base64," + data.IdentityImage;
            document.getElementById("ddlMartialState").value = data.MartialState;
            document.getElementById("txtAddress").value = data.Address;
            document.getElementById("txtPhoneNumber1").value = data.PhoneNo1;
            document.getElementById("txtPhoneNumber2").value = data.PhoneNo2;
            document.getElementById("txtEmail").value = data.Email;
            document.getElementById("ddlClasses").value = data.classes;

            //Birth Date begin
            var strDate = data.BirthDate;
            var date = data.BirthDate.substring(0, strDate.indexOf(" "));
            var lisDate = date.split("/");
            var day = lisDate[0];;
            var mounth = lisDate[1];
            if (lisDate[0].length == 1)
                day = "0" + lisDate[0];
            if (lisDate[1].length == 1)
                mounth = "0" + lisDate[1];
            var validDate = lisDate[2] + "-" + day + "-" + mounth;
            document.getElementById("txtBirthDate").value = validDate;
            //Birth Date end

            //membership Date begin
            var str2Date = data.membershipDate;
            var date2 = data.BirthDate.substring(0, str2Date.indexOf(" "));
            var lisDate2 = date2.split("/");
            var day2 = lisDate2[0];;
            var mounth2 = lisDate2[1];
            if (lisDate2[0].length == 1)
                day2 = "0" + lisDate2[0];
            if (lisDate2[1].length == 1)
                mounth2 = "0" + lisDate2[1];
            var validDate2 = lisDate2[2] + "-" + day2 + "-" + mounth2;
            document.getElementById("txtMemberShipExpired").value = validDate2;
            //membership Date end


            FillSelectUpdate(data.IsTrainer, data.TitleID);
            document.getElementById("txtSalary").value = data.Salary;
        }

    </script>
    <style>
        .row {
            padding-bottom: 10px;
        }
    </style>
</head>

<body>
    <div class="container my-4">
        <div>
            @if (@ViewBag.id == null)
            {
                <div class="emp-heading text-center mb-4  bg-light rounded-lg py-4">
                    <h2 class="text-secondary" id="pageStatus">Insert</h2>
                    <span span class="text-secondary"> Member</span>
                </div>

            }
            else
            {
                <div class="text-center mb-4  bg-light rounded-lg py-4">
                    <h2 class="text-secondary" id="pageStatus">Update</h2>
                    <span span class="text-secondary"> Member</span>
                </div>

            }

        </div>
        @using (Html.BeginForm("Save", "Members", new { empId = @ViewBag.id }, FormMethod.Post,
            new { enctype = "multipart/form-data", @class = "form-horizontal emp-form" }))
        {
            <div class="form-group row ">
                <label for="txtFirstName" class="col-sm-4 control-label">Name:</label>
                <div class="col-sm-8">
                    <input type="text" name="txtFirstName" id="txtFirstName" placeholder="First Name" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtSecondName" class="col-sm-4 control-label">Father Name:</label>
                <div class="col-sm-8">
                    <input type="text" name="txtSecondName" id="txtSecondName" placeholder="Second Name" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtThirdName" class="col-sm-4 control-label">GrandFather Name:</label>
                <div class="col-sm-8">
                    <input type="text" name="txtThirdName" id="txtThirdName" placeholder="Last Name" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtFourthName" class="col-sm-4 control-label">Family Name:</label>
                <div class="col-sm-8">
                    <input type="text" name="txtFourthName" id="txtFourthName" placeholder="Last Name" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="gender" class="col-sm-4 control-label">Gender</label>
                <div class="col-sm-8">
                    <select class="form-control" name="ddlGender" id="ddlGender">
                        <option value="none" selected>--select--</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="nationalID" class="col-sm-4 control-label">National ID</label>
                <div class="col-sm-8">
                    <input type="text" name="txtNationalId" id="txtNationalId" placeholder="National ID" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="personalImage" class="col-sm-4 control-label">Personal Image</label>
                <div class="col-sm-8">
                    <input type="file" id="personImage" name="personImage" onchange="fileSelectedPersonal(this)" class="form-control-file">
                    <img id="imgPersonal" class="img-fluid image-form" src="~/Images/defaultImg.png" />
                </div>
            </div>

            <div class="form-group row">
                <label for="personalImage" class="col-sm-4 control-label">ID Image</label>
                <div class="col-sm-8">
                    <input type="file" id="idImage" name="idImage" onchange="fileSelectedId(this)" class="form-control-file">
                    <img id="imgId" class="img-fluid id-image" src="~/Images/defaultImg.png" />
                </div>
            </div>

            <div class="form-group row">
                <label for="birthDate" class="col-sm-4 control-label">Birth date</label>
                <div class="col-sm-8">
                    <input type="date" id="txtBirthDate" name="txtBirthDate" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="ddlMartialState" class="col-sm-4 control-label">Martial State:</label>
                <div class="col-sm-8">
                    <select class="form-control" name="ddlMartialState" id="ddlMartialState">
                        <option value="none" selected>--select--</option>
                        <option value="Single">Single</option>
                        <option value="Married">Married</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="address" class="col-sm-4 control-label">Address</label>
                <div class="col-sm-8">
                    <input type="text" id="txtAddress" name="txtAddress" placeholder="Address" class="form-control" autofocus>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtPhoneNumber1" class="col-sm-4 control-label">First Phone number </label>
                <div class="col-sm-8">
                    <input type="text" name="txtPhoneNumber1" id="txtPhoneNumber1" placeholder="+9627........" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="txtPhoneNumber2" class="col-sm-4 control-label">Second Phone number </label>
                <div class="col-sm-8">
                    <input type="text" name="txtPhoneNumber2" id="txtPhoneNumber2" placeholder="+9627........" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="txtEmail" class="col-sm-4 control-label">Email* </label>
                <div class="col-sm-8">
                    <input type="email" name="txtEmail" id="txtEmail" placeholder="user@domain.com" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="ddlClasses" class="col-sm-4 control-label">Classes:</label>
                <div class="col-sm-8">
                    <select class="form-control" name="ddlClasses" id="ddlClasses">
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="txtMemberShipExpired" class="col-sm-4 control-label">Membership Expired</label>
                <div class="col-sm-8">
                    <input type="date" id="txtMemberShipExpired" name="txtMemberShipExpired" class="form-control">
                </div>
            </div>

            <div class="button my-2">
                <input type="submit" class="btn btn-form " name="btnSave" id="btnSave" value="Save">
            </div>
        }
    </div>
</body>

</html>

GymManagmentSystem/Views/Members/List.cshtml
@model GymManagmentSystem.Models.MemberModels.MemClassModel
@{
    ViewBag.Title = "List";
}
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .btn {
            background-color: DodgerBlue;
            border: none;
            color: white;
            padding: 2px 6px;
            font-size: 16px;
            cursor: pointer;
        }

        td {
            padding: 3px
        }
    </style>
    <script>
        $(document).ready(function () {

        });

        function Delete(Id) {
            //debugger;
            $.ajax({
                type: "post",
                url: "/Members/Delete",
                data: { id: Id },
                success: function () {
                    location.reload();
                },
                error: function () {
                    alert("failed to delete");
                }
            });
        }
        function Update(Id) {
            window.location.href = window.location.origin + "/Members/Update/" + Id;

        }

        function Enrollment(classId, memberId) {
            $.ajax({
                url: '/Members/Enrollment',
                method: 'get',
                data: {
                    classId: classId,
                    memberId: memberId
                },
                success: function (data) {
                    debugger;
                },
                error: function () {
                    debugger;
                }
            });
        }
    </script>
</head>
<body>
    <div class="container-emp employees">
        <div>
            <h2 class="text-center mb-3 text-secondary bg-light rounded-lg py-3">Member List</h2>
        </div>
        @if (!Model.Mems.Any())
        {
            <h1 style="font:italic;color:red">
                There are no Employees
            </h1>
        }
        else
        {

            foreach (var item in Model.Mems)
            {

                var base64 = Convert.ToBase64String(item.Image);
                var imgSrc = String.Format("data:image/png;base64,{0}", base64);

                <!-- start employees card -->
                <div class="card mb-3" style="max-width: 100%;">
                    <div class="row no-gutters">
                        <!-- actions -->
                        <div class="actions col-md-1">
                            <a onclick="Delete(@item.Id)"><i class="fas fa-user-times "></i></a> @*delete*@
                            <a onclick="Update(@item.Id)"><i class="fas fa-user-edit "></i></a> @*edit*@
                        </div>

                        <!-- image -->
                        <div class="col-md-1 card-img-container">
                            <img src="@imgSrc" class="card-img" alt="...">
                        </div>

                        <!-- content -->
                        <div class="col-md-10">
                            <div class="card-body row">
                                <div class="col-md-2">
                                    <h5 class="card-title">Name</h5>
                                    <p class="card-text text-secondary">@item.Name</p>
                                </div>

                                <div class="col-md-2">
                                    <h5 class="card-title">Phone Number</h5>
                                    <p class="card-text text-secondary">@item.PhoneNumber</p>
                                </div>

                                <div class="col-md-2">
                                    <h5 class="card-title">Start Date</h5>
                                    <p class="card-text text-secondary">@item.StartDate</p>
                                </div>

                                <div class="col-md-2">
                                    <h5 class="card-title">Exbiry Date</h5>
                                    <p class="card-text text-secondary">@item.ExbiryDate</p>
                                </div>
                                <div class="col-md-4">
                                    <h5 class="card-title">Enrollments</h5>
                                    <p class="card-text text-secondary">
                                        <select class="form-control" name="ddlEnrollment" id="ddlEnrollment">
                                            @*@foreach (var clas in Model.Classes)
                                                {
                                                    <option value="@clas.Id" selected>@clas.Name</option>
                                                }*@
                                            @foreach (var clas in item.Classes)
                                            {
                                                <option value="@clas.Id" selected>@clas.Name / @clas.Trainer / @clas.Trainer</option>
                                            }
                                        </select>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- end content -->
                    </div>
                </div>
                <!--  -->
                <!-- end employees card -->
            }

        }
    </div>
</body>
</html>